/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import javax.swing.JButton;
import model.Calculadora;



/**
 *
 * @author Ervin
 */
public class CalculadoraForm extends javax.swing.JFrame {
private final Calculadora mo = new Calculadora();
private boolean freeToStart = true;
    /**
     * Creates new form CalculadoraForm
     */
    public CalculadoraForm() {
        initComponents();
    }
    public Calculadora getCalculadora(){
        return mo;
    }
    public boolean isFreeToStart() {
        return freeToStart;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        screenLabel = new javax.swing.JLabel();
        screenTextField = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ceBoton = new javax.swing.JButton();
        cBoton = new javax.swing.JButton();
        backBoton = new javax.swing.JButton();
        divicionBoton = new javax.swing.JButton();
        sieteBoton = new javax.swing.JButton();
        multiplicacionBoton = new javax.swing.JButton();
        cuatroBoton = new javax.swing.JButton();
        masomenosBoton = new javax.swing.JButton();
        ochoBoton = new javax.swing.JButton();
        nueveBoton = new javax.swing.JButton();
        unoBoton = new javax.swing.JButton();
        cincoBoton = new javax.swing.JButton();
        seisBoton = new javax.swing.JButton();
        restaBoton = new javax.swing.JButton();
        dosBoton = new javax.swing.JButton();
        tresBoton = new javax.swing.JButton();
        sumaBoton = new javax.swing.JButton();
        igualBoton = new javax.swing.JButton();
        ceroBoton = new javax.swing.JButton();
        puntoBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 244, 238));

        screenLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        screenLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        screenLabel.setText("jLabel1");

        screenTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        screenTextField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        screenTextField.setText("jLabel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(screenTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(screenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(screenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(screenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 110));

        jPanel2.setBackground(new java.awt.Color(0, 247, 228));
        jPanel2.setMaximumSize(new java.awt.Dimension(50, 50));
        jPanel2.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 50));

        ceBoton.setText("CE");
        ceBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        ceBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        ceBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        ceBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceBotonActionPerformed(evt);
            }
        });

        cBoton.setText("C");
        cBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        cBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        cBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        cBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBotonActionPerformed(evt);
            }
        });

        backBoton.setText(" ←");
        backBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        backBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        backBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        backBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBotonActionPerformed(evt);
            }
        });

        divicionBoton.setText("/");
        divicionBoton.setAlignmentY(0.0F);
        divicionBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        divicionBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        divicionBoton.setPreferredSize(new java.awt.Dimension(50, 50));

        sieteBoton.setText("7");
        sieteBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        sieteBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        sieteBoton.setPreferredSize(new java.awt.Dimension(50, 50));

        multiplicacionBoton.setText("*");
        multiplicacionBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        multiplicacionBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        multiplicacionBoton.setPreferredSize(new java.awt.Dimension(50, 50));

        cuatroBoton.setText("4");
        cuatroBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        cuatroBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        cuatroBoton.setPreferredSize(new java.awt.Dimension(50, 50));

        masomenosBoton.setText("<html>&plusmn;");
        masomenosBoton.setAlignmentY(0.0F);
        masomenosBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        masomenosBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        masomenosBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        masomenosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masomenosBotonActionPerformed(evt);
            }
        });

        ochoBoton.setText("8");
        ochoBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        ochoBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        ochoBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        ochoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoBotonActionPerformed(evt);
            }
        });

        nueveBoton.setText("9");
        nueveBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        nueveBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        nueveBoton.setPreferredSize(new java.awt.Dimension(50, 5));

        unoBoton.setText("1");
        unoBoton.setAlignmentY(0.0F);
        unoBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        unoBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        unoBoton.setPreferredSize(new java.awt.Dimension(50, 50));

        cincoBoton.setText("5");
        cincoBoton.setAlignmentY(0.0F);
        cincoBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        cincoBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        cincoBoton.setPreferredSize(new java.awt.Dimension(50, 50));

        seisBoton.setText("6");
        seisBoton.setAlignmentY(0.0F);
        seisBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        seisBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        seisBoton.setPreferredSize(new java.awt.Dimension(50, 50));

        restaBoton.setText("-");
        restaBoton.setAlignmentY(0.0F);
        restaBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        restaBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        restaBoton.setPreferredSize(new java.awt.Dimension(50, 50));

        dosBoton.setText("2");
        dosBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        dosBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        dosBoton.setPreferredSize(new java.awt.Dimension(50, 50));

        tresBoton.setText("3");
        tresBoton.setAlignmentY(0.0F);
        tresBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        tresBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        tresBoton.setPreferredSize(new java.awt.Dimension(50, 50));

        sumaBoton.setText("+");
        sumaBoton.setAlignmentY(0.0F);
        sumaBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        sumaBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        sumaBoton.setPreferredSize(new java.awt.Dimension(50, 50));

        igualBoton.setText("=");
        igualBoton.setAlignmentY(0.0F);
        igualBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        igualBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        igualBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        igualBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualBotonActionPerformed(evt);
            }
        });

        ceroBoton.setText("0");
        ceroBoton.setAlignmentY(0.0F);
        ceroBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        ceroBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        ceroBoton.setPreferredSize(new java.awt.Dimension(50, 50));

        puntoBoton.setText(".");
        puntoBoton.setAlignmentY(0.0F);
        puntoBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        puntoBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        puntoBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        puntoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sieteBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ceBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cuatroBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masomenosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cincoBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(cBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ochoBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ceroBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nueveBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(divicionBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multiplicacionBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(seisBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tresBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(puntoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sumaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(restaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(igualBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ceBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(divicionBoton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backBoton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nueveBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sieteBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ochoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(multiplicacionBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuatroBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cincoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seisBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sumaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tresBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(unoBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dosBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masomenosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(igualBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(puntoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ceroBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 310, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void igualBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualBotonActionPerformed
        resolveMathOperation;
    }//GEN-LAST:event_igualBotonActionPerformed

    private void ochoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ochoBotonActionPerformed

    private void puntoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoBotonActionPerformed
        String x  = getScreenText();
        if(x.indexOf(".")== -1){
            setTextToScreen(x + ".");
        }
    }//GEN-LAST:event_puntoBotonActionPerformed

    private void ceBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceBotonActionPerformed
        setTextToScreen("");
    }//GEN-LAST:event_ceBotonActionPerformed
//no entiendo
    private void masomenosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masomenosBotonActionPerformed
        if(!getScreenText().equals("0")){
            Double number = Double.valueOf(getScreenText());
            number = number * -1;
            setTextToScreen(String.valueOf(number));
        }
    }//GEN-LAST:event_masomenosBotonActionPerformed

    private void cBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBotonActionPerformed
        clear();
    }//GEN-LAST:event_cBotonActionPerformed
//tampoco entiendo, si hay mas de un digito borra el de la derecha
    private void backBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBotonActionPerformed
        String x = getScreenText();
        if(!x.equals("0") && x.length() >= 1){
            if(x.length() == 1){
                setTextToScreen("0");
            }
            else{
                setTextToScreen(x.substring(0,x.length()-1));
            }
        }
    }//GEN-LAST:event_backBotonActionPerformed
     private void printNumberActionPerformed(java.awt.event.ActionEvent evt) {                                            
        JButton b = (JButton)evt.getSource();
        if (freeToStart){
            clear();
            setTextToScreen(b.getText());            
        }
        else
        {
            if(!getScreenText().equals("0")){
                setTextToScreen(getScreenText()+ b.getText());
            }
            else
            {
                setTextToScreen(b.getText());
            }            
        }
    }  
    public void setTextToScreen(String content){
        screenTextField.setText(content);
    }
    
    public String getScreenText(){
        return screenTextField.getText();
    }   
    private void resolveMathOperation(){
        mo.setNum2(getScreenText());// por que solo toma Num2
        setTextToScreen(mo.resolve());
        screenLabel.setText(mo.toString());
        freeToStart=true;
    }
    private void resolveMathOperation(boolean showExternal){
        
    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBoton;
    private javax.swing.JButton cBoton;
    private javax.swing.JButton ceBoton;
    private javax.swing.JButton ceroBoton;
    private javax.swing.JButton cincoBoton;
    private javax.swing.JButton cuatroBoton;
    private javax.swing.JButton divicionBoton;
    private javax.swing.JButton dosBoton;
    private javax.swing.JButton igualBoton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton masomenosBoton;
    private javax.swing.JButton multiplicacionBoton;
    private javax.swing.JButton nueveBoton;
    private javax.swing.JButton ochoBoton;
    private javax.swing.JButton puntoBoton;
    private javax.swing.JButton restaBoton;
    private javax.swing.JLabel screenLabel;
    private javax.swing.JLabel screenTextField;
    private javax.swing.JButton seisBoton;
    private javax.swing.JButton sieteBoton;
    private javax.swing.JButton sumaBoton;
    private javax.swing.JButton tresBoton;
    private javax.swing.JButton unoBoton;
    // End of variables declaration//GEN-END:variables

   
}
