/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.views;

import javax.swing.JInternalFrame;
import ni.edu.ni.controllers.MainController;

/**
 *
 * @author Comtech
 */
public class MainFrame extends javax.swing.JFrame {
    MainController mc;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setupController();
    }
    
    private void setupController(){
        mc = new MainController(this);
        this.personMenuItem.addActionListener(mc);
        this.exitButton.addActionListener(mc);
        this.exitMenuItem.addActionListener(mc);
    }
    public void showChild(JInternalFrame frame,boolean maximizeFrame){
        desktop.add(frame);
        frame.setVisible(true);
        if(maximizeFrame){
            desktop.getDesktopManager().maximizeFrame(frame);            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        exitButton = new javax.swing.JButton();
        mainMenuBar = new javax.swing.JMenuBar();
        personaMenuItem = new javax.swing.JMenu();
        personMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Persona");

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitButton.setActionCommand("exit");
        exitButton.setFocusable(false);
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(exitButton);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        personaMenuItem.setText("Persona");

        personMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        personMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/persona.png"))); // NOI18N
        personMenuItem.setText("Persona");
        personMenuItem.setActionCommand("persona");
        personMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personMenuItemActionPerformed(evt);
            }
        });
        personaMenuItem.add(personMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitMenuItem.setText("Salir");
        exitMenuItem.setActionCommand("exit");
        personaMenuItem.add(exitMenuItem);

        mainMenuBar.add(personaMenuItem);

        setJMenuBar(mainMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personMenuItemActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton exitButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem personMenuItem;
    private javax.swing.JMenu personaMenuItem;
    // End of variables declaration//GEN-END:variables
}
